version: "3.8"
services:
  node_frontend:
    container_name: node_frontend
    build: .
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "19006:19006"
    restart: always
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.1.132
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
