version: "3.8"
services:
  expo-frontend:
    image: final-iteration/expo:1.2.0
    hostname: final-iteration
    container_name: expo-frontend
    build: ./app/frontend/
    env_file: 
      - .env
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "19006:19006"
    volumes:
      - ./app/frontend:/usr/src/app
      - node_modules:/usr/src/cache
    restart: always
    environment:
      - "REACT_NATIVE_PACKAGER_HOSTNAME=${REACT_NATIVE_PACKAGER_HOSTNAME}"
      - "EXPO_DEVTOOLS_LISTEN_ADDRESS=${EXPO_DEVTOOLS_LISTEN_ADDRESS}"
    command: /usr/src/app/docker-entrypoint.sh
  mongodb:
    image: mongo:5.0
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes: 
      - mongodb:/data/db
volumes: 
  node_modules:
  mongodb: