version: "3.8"
services:
  mongodb:
    build: ./mongo-db/
    image: final-iteration/mongodb:1.0.0
    hostname: final-iteration
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes: 
      - mongodb:/data/db
  express:
    image: final-iteration/express:1.0.0
    hostname: final-iteration
    container_name: express
    build: ./mongo-api/
    env_file: 
      - .env
    environment:
      - "EXPRESS_API_PORT=${EXPRESS_API_PORT}"
      - "NODE_ENV=${NODE_ENV}"
      - "DATABASE_USER=${DATABASE_USER}"
      - "DATABASE_PW=${DATABASE_PW}"
      - "DATABASE_HOST=${DATABASE_HOST}"
      - "DATABASE_PORT=${DATABASE_PORT}"
      - "DATABASE_NAME=${DATABASE_NAME}"
      - "DATABASE_PROTOCOL=${DATABASE_PROTOCOL}"
      - "DATABASE_COLLECTION=${DATABASE_COLLECTION}"
      - "DATABASE_AUTHSOURCE=${DATABASE_AUTHSOURCE}"
      - "DATABASE_CAPATH=${DATABASE_CAPATH}"
      - "LOCAL_DATABASE_HOST=${LOCAL_DATABASE_HOST}"
      - "LOCAL_DATABASE_PORT=${LOCAL_DATABASE_PORT}"
      - "LOCAL_DATABASE_NAME=${LOCAL_DATABASE_NAME}"
      - "LOCAL_DATABASE_PROTOCOL=${LOCAL_DATABASE_PROTOCOL}"
      - "LOCAL_DATABASE_COLLECTION=${LOCAL_DATABASE_COLLECTION}"
      - "DEBUG=${DEBUG}"
    ports:
      - "3005:3005"
    volumes:
      - ./mongo-api:/usr/src/app
      - api_node_modules:/usr/src/cache
    restart: unless-stopped
  # expo:
  #   image: final-iteration/expo:1.2.0
  #   hostname: final-iteration
  #   container_name: expo
  #   build: ./frontend/
  #   env_file: 
  #     - .env
  #   ports:
  #     - "19000:19000"
  #     - "19001:19001"
  #     - "19002:19002"
  #     - "19006:19006"
  #   volumes:
  #     - ./frontend:/usr/src/app
  #     - frontend_node_modules:/usr/src/cache
  #   restart: always
  #   environment:
  #     - "REACT_NATIVE_PACKAGER_HOSTNAME=${REACT_NATIVE_PACKAGER_HOSTNAME}"
  #     - "EXPO_DEVTOOLS_LISTEN_ADDRESS=${EXPO_DEVTOOLS_LISTEN_ADDRESS}"
  #   command: /usr/src/app/docker-entrypoint.sh
volumes: 
  frontend_node_modules:
  api_node_modules:
  mongodb: