version: "3.8"
services:
  mongo-database:
    image: ucd-emp-wellness-db:lts
    container_name: ucd-emp-wellness-db
    build: ./mongo-db/
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes: 
      - mongodb:/data/db
    networks:
      - dev_network
  express-api:
    image: ucd-emp-wellness-api:lts
    container_name: ucd-emp-wellness-api
    build: ./mongo-api/
    environment:
      - "NODE_ENV=docker"
      - "EXPRESS_API_PORT=${EXPRESS_API_PORT}"
      - "CA_CERTIFICATE_PATH=${CA_CERTIFICATE_PATH}"
      - "DEV_DATABASE_HOST=${DEV_DATABASE_HOST}"
      - "DEV_DATABASE_PORT=${DEV_DATABASE_PORT}"
      - "DEV_DATABASE_NAME=${DEV_DATABASE_NAME}"
      - "DEV_DATABASE_PROTOCOL=${DEV_DATABASE_PROTOCOL}"
      - "DEV_DATABASE_COLLECTION=${DEV_DATABASE_COLLECTION}"
      - "DEBUG=${DEBUG}"
    ports:
      - "3005:3005"
    volumes:
      - ./mongo-api:/usr/src/app
      - api_node_modules:/usr/src/cache
    restart: unless-stopped
    networks:
      - dev_network
    depends_on:
      - mongo-database

volumes: 
  api_node_modules:
  mongodb:

networks:
  dev_network:
    external: true