version: "3.8"
services:
  express-api:
    image: ucd-emp-wellness-api
    hostname: final-iteration
    container_name: ucd-emp-wellness-api
    build: ./mongo-api/
    env_file: 
      - .env
    environment:
      - "EXPRESS_API_PORT=${EXPRESS_API_PORT}"
      - "NODE_ENV=production"
      - "PROD_DATABASE_USER=${PROD_DATABASE_USER}"
      - "PROD_DATABASE_PW=${PROD_DATABASE_PW}"
      - "PROD_DATABASE_HOST=${PROD_DATABASE_HOST}"
      - "PROD_DATABASE_PORT=${PROD_DATABASE_PORT}"
      - "PROD_DATABASE_NAME=${PROD_DATABASE_NAME}"
      - "PROD_DATABASE_PROTOCOL=${PROD_DATABASE_PROTOCOL}"
      - "PROD_DATABASE_COLLECTION=${PROD_DATABASE_COLLECTION}"
      - "PROD_DATABASE_AUTHSOURCE=${PROD_DATABASE_AUTHSOURCE}"
      - "PROD_DATABASE_CAPATH=${PROD_DATABASE_CAPATH}"
      - "DEV_DATABASE_HOST=${DEV_DATABASE_HOST}"
      - "DEV_DATABASE_PORT=${DEV_DATABASE_PORT}"
      - "DEV_DATABASE_NAME=${DEV_DATABASE_NAME}"
      - "DEV_DATABASE_PROTOCOL=${DEV_DATABASE_PROTOCOL}"
      - "DEV_DATABASE_COLLECTION=${DEV_DATABASE_COLLECTION}"
      - "DEBUG=${DEBUG}"
    ports:
      - "3005:3005"
    volumes:
      - ./mongo-api:/usr/src/app
      - api_node_modules:/usr/src/cache
    restart: unless-stopped

volumes:
  api_node_modules: