version: "3.8"
services:
  express-api:
    image: final_iteration_api_prod:lts
    hostname: final-iteration
    container_name: express-api
    build: ./mongo-api/
    environment:
      - "NODE_ENV=production"
      - "EXPRESS_API_PORT=${EXPRESS_API_PORT}"
      - "CA_CERTIFICATE_PATH=${CA_CERTIFICATE_PATH}"
      - "PROD_DATABASE_USER=${PROD_DATABASE_USER}"
      - "PROD_DATABASE_PW=${PROD_DATABASE_PW}"
      - "PROD_DATABASE_HOST=${PROD_DATABASE_HOST}"
      - "PROD_DATABASE_PORT=${PROD_DATABASE_PORT}"
      - "PROD_DATABASE_NAME=${PROD_DATABASE_NAME}"
      - "PROD_DATABASE_PROTOCOL=${PROD_DATABASE_PROTOCOL}"
      - "PROD_DATABASE_COLLECTION=${PROD_DATABASE_COLLECTION}"
      - "PROD_DATABASE_AUTHSOURCE=${PROD_DATABASE_AUTHSOURCE}"
    ports:
      - "3005:3005"
    restart: unless-stopped